# Generated by Django 2.2.4 on 2020-01-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empName', models.CharField(max_length=50)),
                ('empRSA_ID', models.CharField(max_length=13)),
                ('empLName', models.CharField(max_length=50)),
                ('empDOB', models.DateField()),
                ('empPos', models.CharField(max_length=25)),
                ('empHireDt', models.DateField()),
                ('employmentStatus', models.CharField(max_length=10)),
            ],
        ),
    ]
